development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  # url: redis://localhost:6379/1
  # url:  <%=ENV['REDISTOGO_URL']%>
  url:  redis://redistogo:670c5aadc634dd518a84dcdfc35350eb@greeneye.redistogo.com:9583/ 
