# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd342e979e92839a1a506f4cdcc3804d17de43513f6d0a84bef651c9829f15ac3750d6faceec94b2aae6251b3ff12a15b99f836fbc757be12e0d3cc620dcd7f7

test:
  secret_key_base: 355ce61caedf6cb88fed42c8ab0d8d1b6e6a703c5e930ef464c710637a5b8aeb75c028c68a26fa01e2f11a75ad79c9bfd357549e0a0be6f6e214ffa9637ae77a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
